### ISSUE TITLE
Doesn't lock on Stock Android 7.1.1

### ISSUE THREAD

**Issue by CrimsonFork** [SyntaxBlitz/PluckLock#23]
_Sent from my Moto E (4) Plus using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by SyntaxBlitz** [comment]
I notice you have an issue open in parallel with [PluckLockEx](https://github.com/0xFireball/PluckLockEx). That fork is still being maintained (where this one is more-or-less dead), so I'm going to close this issue to consolidate the discussion there.

**Comment by CrimsonFork** [comment]
Yeah, I haven't noticed that one at the time of writing this issue.

On January 8, 2019 2:30:19 PM UTC, Timothy Aveni <notifications@github.com> wrote:
>Closed #23.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SyntaxBlitz/PluckLock/issues/23#event-2060353732

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
